export enum enOperationFrame {
    hidden = 1,
    reliadUrl = 2,
    returnIndex = 3,
    redirectAggiungiIndirizzo = 4,
    redirectITuopiCouponSconto = 5,
    show = 6,
    redirectITuoiOrdini = 7,
    redirectLogin = 8,
    redirectDetaglioOrdini = 9,
    redirectDetaglioLavoro = 10,
    newTagListinoTemplate = 11,
    redirectOtherUri = 12,
    hiddenPage = 13,
    counterCarrello = 14,
    print = 15,
}